import './globals.css'
import { Inter } from 'next/font/google'
import Navigation from '@/components/navigation/Navigation'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Jether B. Balabagno',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} style={{ backgroundColor: "white" }}>
        <Navigation/>
        {children}
      </body>
    </html>
  )
}
